name: math
version: 0.0.0
homepage: https://github.com/morloc-lib/math
synopsis: Basic math functions
description: See README
category: math
license: MIT
author: "Zebulun Arendsee"
maintainer: "zbwrnz@gmail.com"
github: https://github.com/morloc-lib/math
bug-reports: https://github.com/morloc-lib/math
gcc-flags: "-Wall -lm -lgs lgslcblas"
# -Wall -lm -lgs -lcblas
# # cblas is a faster library, but gslcblas comes with gsl, so it more likely to
# # be installed. I need a system for specifying alternative sets of flags.
