name: math
version: 0.0.0
homepage: https://github.com/morloc-lib/math
synopsis: Basic math functions
description: See README
category: math
license: MIT
author: "Zebulun Arendsee"
maintainer: "zbwrnz@gmail.com"
github: https://github.com/morloc-lib/math
bug-reports: https://github.com/morloc-lib/math
gcc-flags: "-lm"
